### ISSUE TITLE
Error importing IdPs configuration from metadata

### ISSUE THREAD

**Issue by fab-codes** [italia/spid-keycloak-provider#76] opened 2024-10-22 12:48 UTC
Hi,

I have Keycloak 23.0.6, so I downloaded release 1.0.17. The jar file in this repo contains an error (resolved here: https://github.com/italia/spid-keycloak-provider/commit/176501afc1c82018b9531471d7efe63c66255a30). So, I downloaded the zip file containing the code and made the modification. After generating the jar file with Maven, I can no longer import the providers through the repo: [keycloak-spid-provider-configuration-client](https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client), and I get this:

![immagine](https://github.com/user-attachments/assets/e140de9c-e50a-4a95-849f-fa4c440c68b5)

Has anyone experienced something like this? Or is it possibly a known issue?

Thanks a lot, and have a great day!

**Comment by nicolabeghin** [comment] 2024-11-12 21:39
hi @fab-codes please note the fixes are not back-ported since this is a community-maintained project! The fix in  176501afc1c82018b9531471d7efe63c66255a30 has been merged in latest releases only ref. https://github.com/italia/spid-keycloak-provider/pull/71

Regarding the error for the configuration client: I would suggest to check keycloak logs before anything else, since without that it would be a wild guess at the root cause :-D also if possible please open the issue in the client repository where more people could help out

**Closed by nicolabeghin** 2024-11-12 21:39 UTC
